name: C/C++ CI

on:
  push:
    branches:
      - master
      - staging
      - develop
      - feature/**
  
  pull_request:
    branches:
      - master
      - staging
      - develop
      - staging

jobs:

  # =========================
  # BUILD
  # =========================

  build:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Build project
      run: make all

  # =========================
  # TEST
  # =========================

  test:

    needs: build

    runs-on: ubuntu-latest

    steps:

    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Run tests
      run: ./bin/teste

  # =========================
  # STAGING DEPLOY
  # =========================

  deploy-staging:

    if: github.ref == 'refs/heads/staging'

    needs: test

    runs-on: ubuntu-latest

    steps:

    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Simulate staging deploy
      run: echo "Deploy realizado em staging"

  # =========================
  # PRODUCTION DEPLOY
  # =========================

  deploy-production:

    if: github.ref == 'refs/heads/master'

    needs: test

    runs-on: ubuntu-latest

    steps:

    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Simulate production deploy
      run: echo "Deploy realizado em produção"
